"""Build src/sim/countryData.ts from the extracted sources (.cache/*.json, see extract.py) and the
hand-researched values in manual.py.  Usage: python3 scripts/country-data/build.py"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from manual import C
CACHE = os.path.join(HERE, '.cache')
wpp = json.load(open(os.path.join(CACHE, 'wpp2026.json')))
vd = json.load(open(os.path.join(CACHE, 'vdem2025.json')))
gov = json.load(open(os.path.join(CACHE, 'govideo.json')))
def q(s): return json.dumps(s, ensure_ascii=False)
def src(t): return '{ v: %s, src: %s }' % (json.dumps(t[0]) if not isinstance(t[0], str) else q(t[0]), q(t[1]))
out = []
out.append("""// Researched data for real countries, compiled on 2026-10-04 (see each value's source).
// Generated by the project's data script from: UN World Population Prospects 2024 (wpp2024 R package),
// V-Dem v16 and V-Party (vdemdata R package), and hand-collected figures from the IMF, World Bank, UNDP,
// Pew Research Center, Freedom House, national statistics offices and others. Do not edit by hand:
// edit the data script's inputs and regenerate.

export interface Sourced<T = number> { v: T; src: string }

export interface CountryRaw {
  id: string;
  name: string;
  iso: string;
  population: number;
  popGrowth: number;
  gdpPPP: number;
  growth: number;
  tfr: Sourced;
  lifeExp: number;
  medianAge: number;
  netMigration: number;
  ageBands: number[];
  urban: number;
  meanSchooling: number;
  expectedSchooling: number;
  freedomHouse: number;
  vdem: { polyarchy: number; rule: number; freexp: number; clphy: number; clpol: number; gender: number; polarization: number; exclusion: number; religiousFreedom: number; stateOwnership: number; propertyRights: number };
  electorate: { econ: number; auth: number; patriot: number; year: number };
  government: { label: string; party: string; year: number; social: number; econ: number; auth: number; relig: number; patriot: number };
  religionImportant: Sourced;
  acceptHomosexuality: Sourced;
  socialTrust: Sourced;
  socialMedia: Sourced;
  individualism: number;
  wealthGini: Sourced;
  taxRevenue: Sourced;
  socialSpending: Sourced;
  militarySpending: number;
  topTaxRate: Sourced;
  religiousPolicy: Sourced<'neutral' | 'favor' | 'theocracy' | 'suppress'>;
  electionYears: number;
  familyPlanning: Sourced;
  institutionalTrust: Sourced | null;
  lastCoup: number | null;
  faiths: { profile: string; share: number; name?: string }[];
  faithSource: string;
}

export const COUNTRY_DATA_DATE = '2026-10-04';

export const COUNTRIES: CountryRaw[] = [""")
for name, c in C.items():
    w = wpp[name]; v = vd[name]; g = gov[name]
    tfr = c['tfr'] if c['tfr'] else (w['tfr'], 'UN World Population Prospects 2024 (2026)')
    faiths = ', '.join('{ profile: %s, share: %s%s }' % (q(p), s, (', name: ' + q(n)) if n else '') for p, s, n in c['faiths'])
    inst = src(c['instTrust']) if c['instTrust'] else 'null'
    out.append(f"""  {{
    id: {q(c['id'])}, name: {q(c['name'])}, iso: {q(c['iso'])},
    population: {round(w['pop_m']*1e6)}, popGrowth: {w['growthrate']}, gdpPPP: {c['gdp']}, growth: {c['growth']},
    tfr: {src(tfr)}, lifeExp: {w['e0']}, medianAge: {w['median']}, netMigration: {w['cnmr']},
    ageBands: [{', '.join(str(round(b, 5)) for b in w['bands'])}],
    urban: {c['urban']}, meanSchooling: {c['mys']}, expectedSchooling: {c['eys']}, freedomHouse: {c['fh']},
    vdem: {{ polyarchy: {v['v2x_polyarchy']}, rule: {v['v2x_rule']}, freexp: {v['v2x_freexp_altinf']}, clphy: {v['v2x_clphy']}, clpol: {v['v2x_clpol']}, gender: {v['v2x_gender']}, polarization: {v['v2cacamps']}, exclusion: {v['v2xpe_exlsocgr']}, religiousFreedom: {v['v2clrelig']}, stateOwnership: {v['v2clstown']}, propertyRights: {v['v2xcl_prpty']} }},
    electorate: {{ econ: {v['elect_econ']}, auth: {v['elect_auth']}, patriot: {v['elect_patriot']}, year: {v['vparty_year']} }},
    government: {{ label: {q(c['gov'][0])}, party: {q(g['parties'][0])}, year: {g['years'][0]}, social: {g['social']}, econ: {g['econ']}, auth: {g['auth']}, relig: {g['relig']}, patriot: {g['patriot']} }},
    religionImportant: {src(c['relImp'])}, acceptHomosexuality: {src(c['accept'])}, socialTrust: {src(c['trust'])}, socialMedia: {src(c['social'])},
    individualism: {c['idv']}, wealthGini: {src(c['wealth'])}, taxRevenue: {src(c['tax'])}, socialSpending: {src(c['welfare'])},
    militarySpending: {c['military']}, topTaxRate: {src(c['topTax'])}, religiousPolicy: {src(c['relPolicy'])}, electionYears: {c['electionYears']},
    familyPlanning: {src(c['famPlan'])}, institutionalTrust: {inst}, lastCoup: {json.dumps(c['lastCoup'])},
    faiths: [{faiths}],
    faithSource: {q(c['faithSrc'])},
  }},""")
out.append("];\n")
open(os.path.join(HERE, '..', '..', 'src', 'sim', 'countryData.ts'), 'w').write('\n'.join(out))
print('written', len(C))
