# Hand-researched values (see sources in each entry). Fetched/compiled 2026-10-04.
S = dict(
  IMF='IMF World Economic Outlook, April 2026 (estimate for 2026)',
  IMFG='IMF World Economic Outlook, April 2026 (real GDP growth, 2026)',
  WB_URB='World Bank WDI, urban population share, 2024',
  HDR='UNDP Human Development Report 2025 (2023 data)',
  FH='Freedom House, Freedom in the World 2026',
  DR='DataReportal, Digital 2026 (active social media user identities / population)',
  HOF='Hofstede, Hofstede & Minkov (2010), Cultures and Organizations: individualism score',
  UBS='UBS Global Wealth Report 2025 (wealth Gini)',
  SIPRI='SIPRI Military Expenditure Database (2024 military burden, % of GDP)',
  OECDREV='OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)',
  SOCX='OECD Social Expenditure Database (public social spending, 2022, % of GDP)',
  PEW19='Pew Research Center Global Attitudes 2019 ("homosexuality should be accepted")',
  PEW24T='Pew Research Center, spring 2024 survey (published Dec 2025): "most people can be trusted"',
  PEW24R='Pew Research Center, spring 2024 survey of 36 countries: religion "very important"',
)
C = {}
C['India'] = dict(id='india', iso='IND', name='India',
  gdp=12801, growth=6.5, urban=36.9, mys=6.9, eys=13.0, fh=62,
  relImp=(77, S['PEW24R']), accept=(37, S['PEW19']), trust=(38, S['PEW24T']), social=(34.1, S['DR']), idv=48, wealth=(74, S['UBS']),
  tax=(18, 'IMF / RBI: general government tax revenue ≈18% of GDP (FY2024–25)'), welfare=(5, 'ILO World Social Protection Report 2024–26: public social protection ≈5% of GDP'),
  military=2.3, topTax=(39, 'Income-tax Act: 30% top rate plus surcharge and cess'), relPolicy=('neutral', 'Constitution of India: secular state (Pew 2017: no official or favoured religion)'),
  electionYears=5, gov=('BJP-led NDA (Narendra Modi, prime minister since 2014)', 'BJP'), famPlan=(0.5, 'UN World Population Policies: policy to lower fertility; National Family Planning Programme since 1952'),
  instTrust=(0.82, 'Gallup World Poll 2023: 82% confident in the national government'), lastCoup=None,
  tfr=None, faiths=[('hindu_india',79.4,None),('muslim_south_asia',15.2,None),('christian_south_asia',2.3,None),('sikh',1.7,None),('buddhist_sea',0.7,None)],
  faithSrc='Pew Research Center 2025, "How the Global Religious Landscape Changed From 2010 to 2020" (2020 shares); Sikh and Buddhist shares from the 2011 census',
)
C['Pakistan'] = dict(id='pakistan', iso='PAK', name='Pakistan',
  gdp=7014, growth=3.6, urban=38.4, mys=4.3, eys=7.9, fh=32,
  relImp=(94, 'Pew Research Center 2018 "The Age Gap in Religion Around the World" (surveys 2008–2017)'), accept=(2, 'Pew Research Center Global Attitudes 2013'), trust=(23, 'World Values Survey wave 7 (2018), "most people can be trusted"'), social=(31.2, S['DR']), idv=14,
  wealth=(74, 'No UBS estimate for Pakistan: regional proxy (India, UBS 2025)'),
  tax=(10.5, 'IMF Article IV 2025: general government tax revenue ≈10.5% of GDP (FY2025)'), welfare=(2, 'ILO World Social Protection Report 2024–26: ≈2% of GDP'),
  military=2.7, topTax=(35, 'Income Tax Ordinance 2001 (salaried top slab 35%)'), relPolicy=('favor', 'Constitution of Pakistan: Islam is the state religion (Pew 2017: official religion)'),
  electionYears=5, gov=('PML-N-led coalition (Shehbaz Sharif, prime minister since 2024)', 'PML(N)'), famPlan=(0.4, 'UN World Population Policies: policy to lower fertility; Population Welfare Programme'),
  instTrust=None, lastCoup=1999,
  tfr=None, faiths=[('muslim_south_asia',96.35,None),('hindu_minority_south_asia',1.61,None),('christian_south_asia',1.37,None)],
  faithSrc='Pakistan Bureau of Statistics, 7th Population and Housing Census 2023',
)
C['Bangladesh'] = dict(id='bangladesh', iso='BGD', name='Bangladesh',
  gdp=10955, growth=4.7, urban=41.2, mys=6.8, eys=12.3, fh=44,
  relImp=(97, S['PEW24R']), accept=(5, 'Not covered by Pew; set near the South Asian Muslim-majority level (Pakistan 2%, Indonesia 9%) — estimate'), trust=(13, 'World Values Survey wave 7 (2018)'), social=(27.4, S['DR']), idv=20,
  wealth=(74, 'No UBS estimate for Bangladesh: regional proxy (India, UBS 2025)'),
  tax=(7.5, 'IMF Article IV 2025: tax revenue ≈7.5% of GDP (FY2025)'), welfare=(2, 'ILO World Social Protection Report 2024–26: ≈2% of GDP'),
  military=1.0, topTax=(30, 'National Board of Revenue, FY2025–26 (top slab 30%)'), relPolicy=('favor', 'Constitution of Bangladesh: Islam is the state religion (Pew 2017: official religion)'),
  electionYears=5, gov=('BNP government (Tarique Rahman, prime minister since February 2026)', 'BNP'), famPlan=(0.6, 'UN World Population Policies: policy to lower fertility; one of the strongest family-planning programmes since the 1970s'),
  instTrust=None, lastCoup=2007,
  tfr=None, faiths=[('muslim_south_asia',91.04,None),('hindu_minority_south_asia',7.95,None),('buddhist_sea',0.61,None),('christian_south_asia',0.30,None)],
  faithSrc='Bangladesh Bureau of Statistics, Population and Housing Census 2022',
)
C['Indonesia'] = dict(id='indonesia', iso='IDN', name='Indonesia',
  gdp=18973, growth=5.0, urban=59.2, mys=8.7, eys=13.3, fh=56,
  relImp=(98, S['PEW24R']), accept=(9, S['PEW19']), trust=(5, S['PEW24T']), social=(59.4, S['DR']), idv=14,
  wealth=(70, 'No UBS estimate for Indonesia: median of the UBS 2025 sample (≈0.70)'),
  tax=(10.1, 'Ministry of Finance: tax ratio ≈10.1% of GDP (2024)'), welfare=(2.5, 'ILO World Social Protection Report 2024–26: ≈2.5% of GDP'),
  military=0.7, topTax=(35, 'Law 7/2021 on Harmonised Taxation (top rate 35%)'), relPolicy=('neutral', 'No state religion; six officially recognised religions under Pancasila'),
  electionYears=5, gov=('Gerindra-led coalition (Prabowo Subianto, president since October 2024)', 'Gerindra'), famPlan=(0.6, 'UN World Population Policies; national family-planning agency BKKBN since 1970'),
  instTrust=None, lastCoup=None,
  tfr=None, faiths=[('muslim_sea',87.1,None),('christian_sea',10.5,'Christians (Protestant & Catholic)'),('hindu_bali',1.7,None),('buddhist_eastasia',0.7,None)],
  faithSrc='Indonesia Ministry of Home Affairs (Dukcapil) population register 2023',
)
C['Nigeria'] = dict(id='nigeria', iso='NGA', name='Nigeria',
  gdp=9994, growth=4.1, urban=54.9, mys=7.6, eys=10.5, fh=44,
  relImp=(93, S['PEW24R']), accept=(7, S['PEW19']), trust=(31, S['PEW24T']), social=(33.8, S['DR']), idv=30,
  wealth=(70, 'No UBS estimate for Nigeria: median of the UBS 2025 sample (≈0.70)'),
  tax=(7, 'IMF Article IV 2025: general government revenue from taxes ≈7% of GDP (after the 2025 GDP rebasing)'), welfare=(0.7, 'ILO World Social Protection Report 2024–26: <1% of GDP'),
  military=0.6, topTax=(25, 'Nigeria Tax Act 2025 (top personal rate 25% from 2026)'), relPolicy=('neutral', 'Constitution of Nigeria: no state religion (Sharia penal codes in 12 northern states)'),
  electionYears=4, gov=('APC government (Bola Tinubu, president since 2023)', 'APC'), famPlan=(0.2, 'UN World Population Policies: policy to lower fertility; modern contraceptive use ≈12% (NDHS 2023–24)'),
  instTrust=(0.25, 'Gallup World Poll 2022: about a quarter confident in the national government'), lastCoup=1993,
  tfr=(4.8, 'Nigeria Demographic and Health Survey 2023–24'), faiths=[('muslim_west_africa',56.1,None),('christian_africa',43.4,None),('folk_african',0.5,None)],
  faithSrc='Pew Research Center 2025 (2020 estimates, based on the Nigeria DHS)',
)
C['Egypt'] = dict(id='egypt', iso='EGY', name='Egypt',
  gdp=23321, growth=4.5, urban=43.0, mys=10.1, eys=13.1, fh=18,
  relImp=(90, 'Derived from Gallup World Poll (97% say religion is important in daily life); Pew has no recent figure'), accept=(3, 'Pew Research Center Global Attitudes 2013'), trust=(7, 'World Values Survey wave 7 (2018)'), social=(41.2, S['DR']), idv=25,
  wealth=(70, 'No UBS estimate for Egypt: median of the UBS 2025 sample (≈0.70)'),
  tax=(12.5, 'IMF Article IV 2025: tax revenue ≈12.5% of GDP (FY2024/25)'), welfare=(4, 'ILO World Social Protection Report 2024–26: ≈4% of GDP'),
  military=1.0, topTax=(27.5, 'Income Tax Law 91/2005 as amended (top rate 27.5%)'), relPolicy=('favor', 'Constitution of Egypt: Islam is the state religion; Sharia is the principal source of law'),
  electionYears=6, gov=('Abdel Fattah el-Sisi (president since 2014; military-backed)', 'NFP'), famPlan=(0.4, 'UN World Population Policies: policy to lower fertility; national family-planning programme'),
  instTrust=None, lastCoup=2013,
  tfr=None, faiths=[('muslim_mena',94.9,None),('christian_mena',5.1,'Christians (mostly Coptic)')],
  faithSrc='Pew Research Center 2025 (2020 estimates); Coptic Church estimates are higher (≈10%)',
)
C['Turkey'] = dict(id='turkey', iso='TUR', name='Türkiye',
  gdp=46672, growth=3.4, urban=77.6, mys=8.9, eys=19.7, fh=32,
  relImp=(71, S['PEW24R']), accept=(25, S['PEW19']), trust=(14, S['PEW24T']), social=(64.8, S['DR']), idv=37, wealth=(73, S['UBS']),
  tax=(21, S['OECDREV']), welfare=(12, 'OECD Social Expenditure Database (≈12% of GDP)'),
  military=1.9, topTax=(40, 'Income Tax Law 193 (top rate 40%)'), relPolicy=('favor', 'Constitutionally secular, but the state Diyanet funds and directs Sunni Islam'),
  electionYears=5, gov=("People's Alliance, AKP–MHP (Recep Tayyip Erdoğan, president since 2014)", "People's All..."), famPlan=(0, 'Pronatalist policy (2025 declared the Year of the Family): no programme to lower fertility'),
  instTrust=None, lastCoup=1980,
  tfr=(1.48, 'TurkStat Birth Statistics 2024'), faiths=[('muslim_turkey',95.0,None),('none_muslim_world',4.5,None),('christian_mena',0.3,None)],
  faithSrc='Pew Research Center 2025 religious-switching survey (95% of adults Muslim, most of the rest unaffiliated)',
)
C['United States'] = dict(id='usa', iso='USA', name='United States',
  gdp=94430, growth=2.3, urban=83.5, mys=13.9, eys=15.9, fh=81,
  relImp=(44, 'Pew Research Center Religious Landscape Study 2023–24'), accept=(72, S['PEW19']), trust=(55, S['PEW24T']), social=(81.1, S['DR']), idv=91, wealth=(77, S['UBS']),
  tax=(25.2, S['OECDREV']), welfare=(22.7, S['SOCX']),
  military=3.4, topTax=(37, 'Internal Revenue Code (federal top rate 37%, plus state taxes)'), relPolicy=('neutral', 'First Amendment: no established religion'),
  electionYears=4, gov=('Republican administration (Donald Trump, president since January 2025)', 'Rep'), famPlan=(0, 'No national policy to lower fertility'),
  instTrust=(0.22, 'Pew Research Center 2024: 22% trust the federal government most of the time'), lastCoup=None,
  tfr=None, faiths=[('evangelical',23,'Evangelical Protestants'),('christian_us',38,'Other Christians (Catholic, mainline, Black Protestant…)'),('none_west',29,'Religiously unaffiliated'),('jewish_diaspora',2,None),('muslim_us',1,None),('hindu_diaspora',1,None),('buddhist_eastasia',1,None)],
  faithSrc='Pew Research Center Religious Landscape Study 2023–24',
)
C['United Kingdom'] = dict(id='uk', iso='GBR', name='United Kingdom',
  gdp=67585, growth=0.8, urban=84.8, mys=13.5, eys=17.8, fh=91,
  relImp=(10, S['PEW24R']), accept=(86, S['PEW19']), trust=(64, S['PEW24T']), social=(81.3, S['DR']), idv=89, wealth=(59, S['UBS']),
  tax=(35.3, S['OECDREV']), welfare=(22.1, S['SOCX']),
  military=2.3, topTax=(45, 'HMRC additional rate 45%'), relPolicy=('neutral', 'Established Church of England is largely symbolic; high religious freedom (V-Dem)'),
  electionYears=5, gov=('Labour government (Andy Burnham, prime minister since July 2026)', 'Lab'), famPlan=(0, 'No national policy to lower fertility'),
  instTrust=(0.27, 'OECD Trust Survey 2024: ≈27% trust the national government'), lastCoup=None,
  tfr=(1.41, 'ONS Births in England and Wales 2024'), faiths=[('christian_weurope',49.4,None),('none_west',40.3,None),('muslim_europe',6.4,None),('hindu_diaspora',1.7,None),('sikh',0.9,None),('jewish_diaspora',0.5,None),('buddhist_eastasia',0.5,None)],
  faithSrc='Censuses 2021 (England & Wales, Northern Ireland) and 2022 (Scotland), excluding "not stated"',
)
C['Germany'] = dict(id='germany', iso='DEU', name='Germany',
  gdp=76747, growth=0.8, urban=77.8, mys=14.3, eys=17.3, fh=93,
  relImp=(11, 'Pew Research Center 2018 (2024 survey: under 20%)'), accept=(86, S['PEW19']), trust=(72, S['PEW24T']), social=(79.0, S['DR']), idv=67, wealth=(67, S['UBS']),
  tax=(38.0, S['OECDREV']), welfare=(26.7, S['SOCX']),
  military=1.9, topTax=(45, 'Einkommensteuergesetz: 45% plus solidarity surcharge'), relPolicy=('neutral', 'Basic Law: no state church (cooperative church–state model)'),
  electionYears=4, gov=('CDU/CSU–SPD coalition (Friedrich Merz, chancellor since May 2025)', 'CDU'), famPlan=(0, 'No national policy to lower fertility'),
  instTrust=(0.39, 'OECD Trust Survey 2024: ≈39% trust the national government'), lastCoup=None,
  tfr=(1.35, 'Destatis 2024'), faiths=[('christian_weurope',48.5,None),('none_west',44.6,None),('muslim_europe',6.6,None),('jewish_diaspora',0.15,None)],
  faithSrc='German Bishops\' Conference and EKD membership statistics 2024; BAMF study on Muslims (5.3–5.6 million); fowid',
)
C['France'] = dict(id='france', iso='FRA', name='France',
  gdp=68563, growth=0.9, urban=82.0, mys=11.7, eys=16.0, fh=89,
  relImp=(18, S['PEW24R']), accept=(86, S['PEW19']), trust=(44, S['PEW24T']), social=(79.1, S['DR']), idv=71, wealth=(57, S['UBS']),
  tax=(43.8, S['OECDREV']), welfare=(31.6, S['SOCX']),
  military=2.1, topTax=(45, 'Code général des impôts: 45% plus 3–4% high-income contribution'), relPolicy=('neutral', 'Laïcité (1905 law): strict separation of state and religion'),
  electionYears=5, gov=('Centrist government (Emmanuel Macron, president since 2017; PM Sébastien Lecornu)', 'LaREM'), famPlan=(0, 'No national policy to lower fertility'),
  instTrust=(0.29, 'OECD Trust Survey 2024: ≈29% trust the national government'), lastCoup=None,
  tfr=(1.56, 'INSEE, Bilan démographique 2025'), faiths=[('christian_weurope',46,None),('none_west',43,None),('muslim_europe',9,None),('jewish_diaspora',0.6,None),('buddhist_eastasia',0.5,None)],
  faithSrc='Pew Research Center 2025 (2020 estimates)',
)
C['Israel'] = dict(id='israel', iso='ISR', name='Israel',
  gdp=59095, growth=3.9, urban=91.5, mys=13.5, eys=14.9, fh=73,
  relImp=(37, S['PEW24R']), accept=(47, S['PEW19']), trust=(49, S['PEW24T']), social=(70, 'DataReportal Digital 2026 (≈70%, estimate)'), idv=54, wealth=(66, S['UBS']),
  tax=(29.5, S['OECDREV']), welfare=(16.5, S['SOCX']),
  military=8.8, topTax=(50, 'Income Tax Ordinance: 47% plus 3% surtax'), relPolicy=('favor', 'Jewish state; religious courts govern marriage (Pew 2017: favoured religion)'),
  electionYears=4, gov=('Likud-led coalition (Benjamin Netanyahu, prime minister since December 2022); election due 27 October 2026', 'L'), famPlan=(0, 'Pronatalist policy: no programme to lower fertility'),
  instTrust=None, lastCoup=None,
  tfr=(2.9, 'Israel Central Bureau of Statistics 2024'), faiths=[('jewish_israel',61.5,'Jews (non-Haredi)'),('jewish_orthodox',14.3,'Haredi Jews'),('muslim_mena',18.4,'Muslims'),('christian_mena',2.0,None),('druze',1.6,None),('none_west',2.2,'No religion recorded')],
  faithSrc='Israel Central Bureau of Statistics, end of 2025 (Jews & others 78.3%, Arabs 21.7%); Haredi share 14.3% (Israel Democracy Institute)',
)
C['Brazil'] = dict(id='brazil', iso='BRA', name='Brazil',
  gdp=24428, growth=1.9, urban=88.0, mys=8.4, eys=15.8, fh=73,
  relImp=(72, 'Pew Research Center 2018 (2024: 87% of Brazilian Christians)'), accept=(67, S['PEW19']), trust=(20, 'Pew Research Center spring 2024 (under 25%; ≈20%)'), social=(67.9, S['DR']), idv=38, wealth=(81, S['UBS']),
  tax=(32, 'OECD Revenue Statistics in Latin America 2025 (≈32% of GDP)'), welfare=(16, 'ILO World Social Protection Report 2024–26: ≈16% of GDP'),
  military=1.1, topTax=(27.5, 'Receita Federal (top rate 27.5%)'), relPolicy=('neutral', 'Constitution of Brazil: secular state'),
  electionYears=4, gov=('PT-led government (Luiz Inácio Lula da Silva, president since 2023); election 4 October 2026', 'PT'), famPlan=(0, 'No national policy to lower fertility'),
  instTrust=None, lastCoup=1964,
  tfr=None, faiths=[('catholic_latam',56.7,None),('evangelical',26.9,'Evangelicals'),('none_west',9.3,'No religion'),('spiritist_brazil',2.8,None)],
  faithSrc='IBGE, Census 2022 religion results (published June 2025), people aged 10+',
)
