// Calibrated settings for real countries. Generated by `npm run fit-countries`; do not edit by hand.

export interface CountryFit {
  fertilityNorm: number;
  healthSpend: number;
  education: number;
  growthMomentum: number;
  immigration: number;
  emigrationScale: number;
  startHealth: number;
  contraceptionShift?: number;
  diseaseBurden?: number;
  /** Family-size tendency of faith groups whose fertility is calibrated (by profile id). */
  groupFertility?: Record<string, number>;
  /** What the calibrated simulation produced in its first years, for comparison with the targets. */
  achieved: { tfr: number; lifeExp: number; meanSchooling: number; gdpGrowthPerPerson: number; netMigration: number; medianAge: number; groupRatio?: Record<string, number> } | null;
}

export const COUNTRY_FIT: Record<string, CountryFit> = {
  "india": {"fertilityNorm": -1.313, "healthSpend": 0.224, "education": 8, "growthMomentum": 4.599, "immigration": 0.03, "emigrationScale": 0.187, "startHealth": 0.763, "contraceptionShift": 0.4, "groupFertility": {"muslim_south_asia": -0.672, "christian_south_asia": -0.298, "sikh": -0.41}, "achieved": {"tfr": 1.91, "lifeExp": 73.4, "meanSchooling": 6.9, "gdpGrowthPerPerson": 4.73, "netMigration": -0.3, "medianAge": 30.5, "groupRatio": {"muslim_south_asia": 1.18, "christian_south_asia": 1.15, "sikh": 1.11}}},
  "pakistan": {"fertilityNorm": -0.74, "healthSpend": 0.113, "education": 6.14, "growthMomentum": 1.154, "immigration": 0.03, "emigrationScale": 3.484, "startHealth": 0.757, "contraceptionShift": 0.313, "achieved": {"tfr": 3.42, "lifeExp": 67.2, "meanSchooling": 4.3, "gdpGrowthPerPerson": 1.7, "netMigration": -4.47, "medianAge": 21.8}},
  "bangladesh": {"fertilityNorm": -1.624, "healthSpend": 0.419, "education": 9.02, "growthMomentum": 2.761, "immigration": 0.03, "emigrationScale": 1.14, "startHealth": 0.765, "contraceptionShift": 0.4, "achieved": {"tfr": 2.11, "lifeExp": 74.8, "meanSchooling": 6.8, "gdpGrowthPerPerson": 4.19, "netMigration": -2.25, "medianAge": 27.5}},
  "indonesia": {"fertilityNorm": -1, "healthSpend": 0, "education": 9.96, "growthMomentum": 3.263, "immigration": 0.03, "emigrationScale": 0.108, "startHealth": 0.763, "diseaseBurden": 0, "achieved": {"tfr": 2.06, "lifeExp": 71.1, "meanSchooling": 8.8, "gdpGrowthPerPerson": 4.25, "netMigration": -0.14, "medianAge": 31.5}},
  "nigeria": {"fertilityNorm": -0.2, "healthSpend": 0, "education": 9.22, "growthMomentum": 0.252, "immigration": 0.03, "emigrationScale": 0.077, "startHealth": 0.74, "contraceptionShift": -0.095, "diseaseBurden": 0.235, "achieved": {"tfr": 4.79, "lifeExp": 55.6, "meanSchooling": 7.5, "gdpGrowthPerPerson": 1.57, "netMigration": -0.14, "medianAge": 19.5}},
  "egypt": {"fertilityNorm": 0.188, "healthSpend": 0, "education": 11.66, "growthMomentum": 0.763, "immigration": 0.03, "emigrationScale": 0.232, "startHealth": 0.757, "diseaseBurden": 0.017, "achieved": {"tfr": 2.7, "lifeExp": 71.4, "meanSchooling": 10.1, "gdpGrowthPerPerson": 2.46, "netMigration": -0.51, "medianAge": 25.5}},
  "turkey": {"fertilityNorm": -1.967, "healthSpend": 0.197, "education": 10.17, "growthMomentum": 3.18, "immigration": 0.03, "emigrationScale": 4.15, "startHealth": 0.766, "contraceptionShift": 0.4, "achieved": {"tfr": 1.5, "lifeExp": 79.1, "meanSchooling": 8.9, "gdpGrowthPerPerson": 3.05, "netMigration": -2.6, "medianAge": 35.5}},
  "usa": {"fertilityNorm": 0.611, "healthSpend": 0.193, "education": 15.26, "growthMomentum": -0.783, "immigration": 0.477, "emigrationScale": 1, "startHealth": 0.765, "groupFertility": {"evangelical": -1.314, "christian_us": -0.78}, "achieved": {"tfr": 1.6, "lifeExp": 78.7, "meanSchooling": 13.9, "gdpGrowthPerPerson": 1.73, "netMigration": 3.51, "medianAge": 39.8, "groupRatio": {"evangelical": 1.21, "christian_us": 1.1}}},
  "uk": {"fertilityNorm": 0.243, "healthSpend": 0.364, "education": 14.73, "growthMomentum": -2.132, "immigration": 0.704, "emigrationScale": 1, "startHealth": 0.768, "groupFertility": {"muslim_europe": 0.08}, "achieved": {"tfr": 1.38, "lifeExp": 82, "meanSchooling": 13.5, "gdpGrowthPerPerson": 0.4, "netMigration": 5.37, "medianAge": 41.2, "groupRatio": {"muslim_europe": 1.81}}},
  "germany": {"fertilityNorm": 0.211, "healthSpend": 0.366, "education": 15.5, "growthMomentum": 0.186, "immigration": 0.305, "emigrationScale": 1, "startHealth": 0.773, "groupFertility": {"muslim_europe": -0.577}, "achieved": {"tfr": 1.31, "lifeExp": 81.8, "meanSchooling": 14.3, "gdpGrowthPerPerson": 1.38, "netMigration": 1.88, "medianAge": 46.8, "groupRatio": {"muslim_europe": 1.43}}},
  "france": {"fertilityNorm": 0.067, "healthSpend": 0.524, "education": 12.58, "growthMomentum": -0.836, "immigration": 0.224, "emigrationScale": 1, "startHealth": 0.776, "groupFertility": {"muslim_europe": -0.703}, "achieved": {"tfr": 1.59, "lifeExp": 84.1, "meanSchooling": 11.7, "gdpGrowthPerPerson": 0.95, "netMigration": 1.29, "medianAge": 43.5, "groupRatio": {"muslim_europe": 1.47}}},
  "israel": {"fertilityNorm": 0.16, "healthSpend": 0.501, "education": 14.23, "growthMomentum": 0.561, "immigration": 0.271, "emigrationScale": 1, "startHealth": 0.771, "groupFertility": {"jewish_orthodox": 5, "muslim_mena": 0.312, "christian_mena": -0.589, "druze": -0.146, "none_west": -0.099}, "achieved": {"tfr": 2.89, "lifeExp": 83.3, "meanSchooling": 13.5, "gdpGrowthPerPerson": 2.66, "netMigration": 1.52, "medianAge": 30.5, "groupRatio": {"jewish_orthodox": 2.72, "muslim_mena": 1.19, "christian_mena": 0.66, "druze": 0.94, "none_west": 0.53}}},
  "brazil": {"fertilityNorm": -2, "healthSpend": 0.247, "education": 9.41, "growthMomentum": 0.558, "immigration": 0.03, "emigrationScale": 0.482, "startHealth": 0.77, "contraceptionShift": 0.4, "achieved": {"tfr": 1.63, "lifeExp": 75.9, "meanSchooling": 8.4, "gdpGrowthPerPerson": 1.47, "netMigration": -0.87, "medianAge": 36.5}},
};
