// Calibrated settings for real countries. Generated by `npm run fit-countries`; do not edit by hand.

export interface CountryFit {
  fertilityNorm: number;
  healthSpend: number;
  education: number;
  growthMomentum: number;
  immigration: number;
  emigrationScale: number;
  startHealth: number;
  contraceptionShift?: number;
  diseaseBurden?: number;
  /** What the calibrated simulation produced in its first years, for comparison with the targets. */
  achieved: { tfr: number; lifeExp: number; meanSchooling: number; gdpGrowthPerPerson: number; netMigration: number; medianAge: number } | null;
}

export const COUNTRY_FIT: Record<string, CountryFit> = {
  "india": {"fertilityNorm": -1.609, "healthSpend": 0.263, "education": 8.01, "immigration": 0.03, "emigrationScale": 0.202, "contraceptionShift": 0.4, "growthMomentum": 4.4, "startHealth": 0.75, "achieved": {"tfr": 1.94, "lifeExp": 73, "meanSchooling": 6.9, "gdpGrowthPerPerson": 5.4, "netMigration": -0.38, "medianAge": 30.5}},
  "pakistan": {"fertilityNorm": -1.2, "healthSpend": 0.213, "education": 6.08, "immigration": 0.03, "emigrationScale": 3.399, "contraceptionShift": 0.313, "growthMomentum": 0.95, "startHealth": 0.75, "achieved": {"tfr": 3.44, "lifeExp": 67.9, "meanSchooling": 4.3, "gdpGrowthPerPerson": 1.95, "netMigration": -4.28, "medianAge": 22.2}},
  "bangladesh": {"fertilityNorm": -1.824, "healthSpend": 0.453, "education": 9.11, "immigration": 0.03, "emigrationScale": 1.153, "contraceptionShift": 0.4, "growthMomentum": 2.16, "startHealth": 0.75, "achieved": {"tfr": 2.09, "lifeExp": 74.6, "meanSchooling": 6.9, "gdpGrowthPerPerson": 3.16, "netMigration": -2.02, "medianAge": 27.5}},
  "indonesia": {"fertilityNorm": -1.1, "healthSpend": 0, "education": 9.87, "immigration": 0.03, "emigrationScale": 0.176, "diseaseBurden": 0.006, "growthMomentum": 3.03, "startHealth": 0.75, "achieved": {"tfr": 2.1, "lifeExp": 70.5, "meanSchooling": 8.7, "gdpGrowthPerPerson": 4.03, "netMigration": -0.33, "medianAge": 31.8}},
  "nigeria": {"fertilityNorm": 1.485, "healthSpend": 0, "education": 9.39, "immigration": 0.03, "emigrationScale": 0.168, "contraceptionShift": -0.095, "diseaseBurden": 0.189, "growthMomentum": 0.58, "startHealth": 0.75, "achieved": {"tfr": 4.75, "lifeExp": 55.4, "meanSchooling": 7.7, "gdpGrowthPerPerson": 1.58, "netMigration": -0.29, "medianAge": 19.5}},
  "egypt": {"fertilityNorm": -0.06, "healthSpend": 0.006, "education": 11.67, "immigration": 0.03, "emigrationScale": 0.27, "growthMomentum": 1.99, "startHealth": 0.75, "achieved": {"tfr": 2.67, "lifeExp": 72.7, "meanSchooling": 10, "gdpGrowthPerPerson": 2.99, "netMigration": -0.56, "medianAge": 26.2}},
  "turkey": {"fertilityNorm": -2, "healthSpend": 0.149, "education": 10.17, "immigration": 0.03, "emigrationScale": 4.393, "contraceptionShift": 0.4, "growthMomentum": 1.63, "startHealth": 0.75, "achieved": {"tfr": 1.58, "lifeExp": 77.4, "meanSchooling": 8.9, "gdpGrowthPerPerson": 2.63, "netMigration": -2.53, "medianAge": 35.2}},
  "usa": {"fertilityNorm": 0.371, "healthSpend": 0.208, "education": 15.27, "immigration": 0.503, "emigrationScale": 1, "growthMomentum": 0.67, "startHealth": 0.75, "achieved": {"tfr": 1.57, "lifeExp": 79.5, "meanSchooling": 13.9, "gdpGrowthPerPerson": 1.67, "netMigration": 3.38, "medianAge": 39.8}},
  "uk": {"fertilityNorm": 0.446, "healthSpend": 0.35, "education": 14.66, "immigration": 0.68, "emigrationScale": 1, "growthMomentum": -0.75, "startHealth": 0.75, "achieved": {"tfr": 1.45, "lifeExp": 82.1, "meanSchooling": 13.5, "gdpGrowthPerPerson": 0.25, "netMigration": 5.26, "medianAge": 41.5}},
  "germany": {"fertilityNorm": 0.29, "healthSpend": 0.324, "education": 15.53, "immigration": 0.293, "emigrationScale": 1, "growthMomentum": -0.15, "startHealth": 0.75, "achieved": {"tfr": 1.35, "lifeExp": 81.4, "meanSchooling": 14.4, "gdpGrowthPerPerson": 0.85, "netMigration": 1.85, "medianAge": 47.2}},
  "france": {"fertilityNorm": 0.022, "healthSpend": 0.533, "education": 12.63, "immigration": 0.23, "emigrationScale": 1, "growthMomentum": -0.48, "startHealth": 0.75, "achieved": {"tfr": 1.56, "lifeExp": 84.8, "meanSchooling": 11.7, "gdpGrowthPerPerson": 0.52, "netMigration": 1.23, "medianAge": 43.5}},
  "israel": {"fertilityNorm": 0.796, "healthSpend": 0.431, "education": 14.24, "immigration": 0.264, "emigrationScale": 1, "growthMomentum": 1.27, "startHealth": 0.75, "achieved": {"tfr": 2.91, "lifeExp": 82.4, "meanSchooling": 13.5, "gdpGrowthPerPerson": 2.27, "netMigration": 1.45, "medianAge": 30.5}},
  "brazil": {"fertilityNorm": -2, "healthSpend": 0.287, "education": 9.35, "immigration": 0.03, "emigrationScale": 0.591, "contraceptionShift": 0.36, "growthMomentum": 0.5, "startHealth": 0.75, "achieved": {"tfr": 1.69, "lifeExp": 77.2, "meanSchooling": 8.3, "gdpGrowthPerPerson": 1.5, "netMigration": -1.11, "medianAge": 36.5}},
};
