// Calibrated settings for real countries. Generated by `npm run fit-countries`; do not edit by hand.

export interface CountryFit {
  fertilityNorm: number;
  healthSpend: number;
  education: number;
  growthMomentum: number;
  immigration: number;
  emigrationScale: number;
  startHealth: number;
  contraceptionShift?: number;
  diseaseBurden?: number;
  /** Family-size tendency of faith groups whose fertility is calibrated (by profile id). */
  groupFertility?: Record<string, number>;
  /** What the calibrated simulation produced in its first years, for comparison with the targets. */
  achieved: { tfr: number; lifeExp: number; meanSchooling: number; gdpGrowthPerPerson: number; netMigration: number; medianAge: number; groupRatio?: Record<string, number> } | null;
}

export const COUNTRY_FIT: Record<string, CountryFit> = {
  "india": {"fertilityNorm": -1.463, "healthSpend": 0.186, "education": 8, "growthMomentum": 5.006, "immigration": 0.03, "emigrationScale": 0.181, "startHealth": 0.763, "contraceptionShift": 0.4, "groupFertility": {"muslim_south_asia": -0.608, "christian_south_asia": -0.443, "sikh": -0.668}, "achieved": {"tfr": 1.93, "lifeExp": 72.4, "meanSchooling": 6.9, "gdpGrowthPerPerson": 4.94, "netMigration": -0.33, "medianAge": 30.5, "groupRatio": {"muslim_south_asia": 1.18, "christian_south_asia": 0.95, "sikh": 0.89}}},
  "pakistan": {"fertilityNorm": -0.74, "healthSpend": 0.113, "education": 6.14, "growthMomentum": 1.154, "immigration": 0.03, "emigrationScale": 3.484, "startHealth": 0.757, "contraceptionShift": 0.313, "achieved": {"tfr": 3.42, "lifeExp": 67.2, "meanSchooling": 4.3, "gdpGrowthPerPerson": 1.7, "netMigration": -4.47, "medianAge": 21.8}},
  "bangladesh": {"fertilityNorm": -1.624, "healthSpend": 0.419, "education": 9.02, "growthMomentum": 2.761, "immigration": 0.03, "emigrationScale": 1.14, "startHealth": 0.765, "contraceptionShift": 0.4, "achieved": {"tfr": 2.11, "lifeExp": 74.8, "meanSchooling": 6.8, "gdpGrowthPerPerson": 4.19, "netMigration": -2.25, "medianAge": 27.5}},
  "indonesia": {"fertilityNorm": -1, "healthSpend": 0, "education": 9.96, "growthMomentum": 3.263, "immigration": 0.03, "emigrationScale": 0.108, "startHealth": 0.763, "diseaseBurden": 0, "achieved": {"tfr": 2.06, "lifeExp": 71.1, "meanSchooling": 8.8, "gdpGrowthPerPerson": 4.25, "netMigration": -0.14, "medianAge": 31.5}},
  "nigeria": {"fertilityNorm": -0.2, "healthSpend": 0, "education": 9.22, "growthMomentum": 0.252, "immigration": 0.03, "emigrationScale": 0.077, "startHealth": 0.74, "contraceptionShift": -0.095, "diseaseBurden": 0.235, "achieved": {"tfr": 4.79, "lifeExp": 55.6, "meanSchooling": 7.5, "gdpGrowthPerPerson": 1.57, "netMigration": -0.14, "medianAge": 19.5}},
  "egypt": {"fertilityNorm": 0.188, "healthSpend": 0, "education": 11.66, "growthMomentum": 0.763, "immigration": 0.03, "emigrationScale": 0.232, "startHealth": 0.757, "diseaseBurden": 0.017, "achieved": {"tfr": 2.7, "lifeExp": 71.4, "meanSchooling": 10.1, "gdpGrowthPerPerson": 2.46, "netMigration": -0.51, "medianAge": 25.5}},
  "turkey": {"fertilityNorm": -1.967, "healthSpend": 0.197, "education": 10.17, "growthMomentum": 3.18, "immigration": 0.03, "emigrationScale": 4.15, "startHealth": 0.766, "contraceptionShift": 0.4, "achieved": {"tfr": 1.5, "lifeExp": 79.1, "meanSchooling": 8.9, "gdpGrowthPerPerson": 3.05, "netMigration": -2.6, "medianAge": 35.5}},
  "usa": {"fertilityNorm": 0.547, "healthSpend": 0.204, "education": 15.26, "growthMomentum": -0.666, "immigration": 0.485, "emigrationScale": 1, "startHealth": 0.766, "groupFertility": {"evangelical": -1.413, "christian_us": -0.721}, "achieved": {"tfr": 1.63, "lifeExp": 79.5, "meanSchooling": 13.9, "gdpGrowthPerPerson": 2.16, "netMigration": 3.28, "medianAge": 39.5, "groupRatio": {"evangelical": 1.24, "christian_us": 1.24}}},
  "uk": {"fertilityNorm": 0.231, "healthSpend": 0.365, "education": 14.73, "growthMomentum": -1.682, "immigration": 0.722, "emigrationScale": 1, "startHealth": 0.769, "groupFertility": {"muslim_europe": -0.159}, "achieved": {"tfr": 1.42, "lifeExp": 81.5, "meanSchooling": 13.5, "gdpGrowthPerPerson": 0.55, "netMigration": 5.5, "medianAge": 41.5, "groupRatio": {"muslim_europe": 1.65}}},
  "germany": {"fertilityNorm": 0.149, "healthSpend": 0.378, "education": 15.5, "growthMomentum": 0.055, "immigration": 0.291, "emigrationScale": 1, "startHealth": 0.774, "groupFertility": {"muslim_europe": -0.626}, "achieved": {"tfr": 1.33, "lifeExp": 82.2, "meanSchooling": 14.4, "gdpGrowthPerPerson": 1.42, "netMigration": 1.77, "medianAge": 46.8, "groupRatio": {"muslim_europe": 1.35}}},
  "france": {"fertilityNorm": 0.008, "healthSpend": 0.506, "education": 12.58, "growthMomentum": -1.291, "immigration": 0.237, "emigrationScale": 1, "startHealth": 0.776, "groupFertility": {"muslim_europe": -0.739}, "achieved": {"tfr": 1.57, "lifeExp": 83.4, "meanSchooling": 11.7, "gdpGrowthPerPerson": 0.18, "netMigration": 1.52, "medianAge": 43.5, "groupRatio": {"muslim_europe": 1.56}}},
  "israel": {"fertilityNorm": -0.051, "healthSpend": 0.455, "education": 14.23, "growthMomentum": -0.134, "immigration": 0.257, "emigrationScale": 1, "startHealth": 0.772, "groupFertility": {"jewish_orthodox": 5.389, "muslim_mena": 0.245, "christian_mena": -0.528, "druze": -0.486, "none_west": -0.077}, "achieved": {"tfr": 2.9, "lifeExp": 83.1, "meanSchooling": 13.5, "gdpGrowthPerPerson": 1.56, "netMigration": 1.25, "medianAge": 30.5, "groupRatio": {"jewish_orthodox": 2.96, "muslim_mena": 1.26, "christian_mena": 0.71, "druze": 0.81, "none_west": 0.5}}},
  "brazil": {"fertilityNorm": -2, "healthSpend": 0.247, "education": 9.41, "growthMomentum": 0.558, "immigration": 0.03, "emigrationScale": 0.482, "startHealth": 0.77, "contraceptionShift": 0.4, "achieved": {"tfr": 1.63, "lifeExp": 75.9, "meanSchooling": 8.4, "gdpGrowthPerPerson": 1.47, "netMigration": -0.87, "medianAge": 36.5}},
};
