// Researched data for real countries, compiled on 2026-10-04 (see each value's source).
// Generated by the project's data script from: UN World Population Prospects 2024 (wpp2024 R package),
// V-Dem v16 and V-Party (vdemdata R package), and hand-collected figures from the IMF, World Bank, UNDP,
// Pew Research Center, Freedom House, national statistics offices and others. Do not edit by hand:
// edit the data script's inputs and regenerate.

export interface Sourced<T = number> { v: T; src: string }

export interface CountryRaw {
  id: string;
  name: string;
  iso: string;
  population: number;
  popGrowth: number;
  gdpPPP: number;
  growth: number;
  tfr: Sourced;
  lifeExp: number;
  medianAge: number;
  netMigration: number;
  ageBands: number[];
  urban: number;
  meanSchooling: number;
  expectedSchooling: number;
  freedomHouse: number;
  vdem: { polyarchy: number; rule: number; freexp: number; clphy: number; clpol: number; gender: number; polarization: number; exclusion: number; religiousFreedom: number; stateOwnership: number; propertyRights: number };
  electorate: { econ: number; auth: number; patriot: number; year: number };
  government: { label: string; party: string; year: number; social: number; econ: number; auth: number; relig: number; patriot: number };
  religionImportant: Sourced;
  acceptHomosexuality: Sourced;
  socialTrust: Sourced;
  socialMedia: Sourced;
  individualism: number;
  wealthGini: Sourced;
  taxRevenue: Sourced;
  socialSpending: Sourced;
  militarySpending: number;
  topTaxRate: Sourced;
  religiousPolicy: Sourced<'neutral' | 'favor' | 'theocracy' | 'suppress'>;
  electionYears: number;
  familyPlanning: Sourced;
  institutionalTrust: Sourced | null;
  lastCoup: number | null;
  faiths: { profile: string; share: number; name?: string }[];
  faithSource: string;
  /** Children per woman by faith group, where a survey reports it; calibrated as ratios to the reference group(s). */
  groupFertility: { ref: string[]; tfr: Record<string, number>; src: string } | null;
}

export const COUNTRY_DATA_DATE = '2026-10-04';

export const COUNTRIES: CountryRaw[] = [
  {
    id: "india", name: "India", iso: "IND",
    population: 1482960000, popGrowth: 0.86, gdpPPP: 12801, growth: 6.5,
    tfr: { v: 1.93, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 72.7, medianAge: 30.4, netMigration: -0.3,
    ageBands: [0.07602, 0.0779, 0.08193, 0.08497, 0.08659, 0.08576, 0.08181, 0.07758, 0.07116, 0.06185, 0.05377, 0.04555, 0.03786, 0.03017, 0.0221, 0.01338, 0.0069, 0.00327, 0.00115, 0.00025, 3e-05],
    urban: 36.9, meanSchooling: 6.9, expectedSchooling: 13.0, freedomHouse: 62,
    vdem: { polyarchy: 0.377, rule: 0.397, freexp: 0.458, clphy: 0.511, clpol: 0.465, gender: 0.658, polarization: 2.08, exclusion: 0.658, religiousFreedom: -0.14, stateOwnership: 0.151, propertyRights: 0.77 },
    electorate: { econ: 0.66, auth: 0.259, patriot: 0.741, year: 2019 },
    government: { label: "BJP-led NDA (Narendra Modi, prime minister since 2014)", party: "BJP", year: 2019, social: 0.344, econ: 0.783, auth: 0.446, relig: 0.708, patriot: 0.845 },
    religionImportant: { v: 77, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 37, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 38, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 34.1, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 48, wealthGini: { v: 74, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 18, src: "IMF / RBI: general government tax revenue ≈18% of GDP (FY2024–25)" }, socialSpending: { v: 5, src: "ILO World Social Protection Report 2024–26: public social protection ≈5% of GDP" },
    militarySpending: 2.3, topTaxRate: { v: 39, src: "Income-tax Act: 30% top rate plus surcharge and cess" }, religiousPolicy: { v: "neutral", src: "Constitution of India: secular state (Pew 2017: no official or favoured religion)" }, electionYears: 5,
    familyPlanning: { v: 0.5, src: "UN World Population Policies: policy to lower fertility; National Family Planning Programme since 1952" }, institutionalTrust: { v: 0.82, src: "Gallup World Poll 2023: 82% confident in the national government" }, lastCoup: null,
    faiths: [{ profile: "hindu_india", share: 79.4 }, { profile: "muslim_south_asia", share: 15.2 }, { profile: "christian_south_asia", share: 2.3 }, { profile: "sikh", share: 1.7 }, { profile: "buddhist_sea", share: 0.7 }],
    faithSource: "Pew Research Center 2025, \"How the Global Religious Landscape Changed From 2010 to 2020\" (2020 shares); Sikh and Buddhist shares from the 2011 census",
    groupFertility: { ref: ["hindu_india"], tfr: { hindu_india: 1.94, muslim_south_asia: 2.36, christian_south_asia: 1.88, sikh: 1.61, buddhist_sea: 1.39 }, src: "National Family Health Survey (NFHS-5), 2019–21: children per woman by religion (national 2.0)" },
  },
  {
    id: "pakistan", name: "Pakistan", iso: "PAK",
    population: 261360000, popGrowth: 1.59, gdpPPP: 7014, growth: 3.6,
    tfr: { v: 3.44, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 68.1, medianAge: 21.9, netMigration: -4.42,
    ageBands: [0.12374, 0.11752, 0.11437, 0.10888, 0.092, 0.08163, 0.07061, 0.06197, 0.05293, 0.04284, 0.03503, 0.02916, 0.02446, 0.01902, 0.01266, 0.00733, 0.00405, 0.00143, 0.00031, 3e-05, 0.0],
    urban: 38.4, meanSchooling: 4.3, expectedSchooling: 7.9, freedomHouse: 32,
    vdem: { polyarchy: 0.302, rule: 0.261, freexp: 0.559, clphy: 0.364, clpol: 0.502, gender: 0.524, polarization: 0.986, exclusion: 0.431, religiousFreedom: -0.738, stateOwnership: 0.417, propertyRights: 0.763 },
    electorate: { econ: 0.587, auth: 0.183, patriot: 0.499, year: 2018 },
    government: { label: "PML-N-led coalition (Shehbaz Sharif, prime minister since 2024)", party: "PML(N)", year: 2018, social: 0.413, econ: 0.583, auth: 0.45, relig: 0.488, patriot: 0.526 },
    religionImportant: { v: 94, src: "Pew Research Center 2018 \"The Age Gap in Religion Around the World\" (surveys 2008–2017)" }, acceptHomosexuality: { v: 2, src: "Pew Research Center Global Attitudes 2013" }, socialTrust: { v: 23, src: "World Values Survey wave 7 (2018), \"most people can be trusted\"" }, socialMedia: { v: 31.2, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 14, wealthGini: { v: 74, src: "No UBS estimate for Pakistan: regional proxy (India, UBS 2025)" }, taxRevenue: { v: 10.5, src: "IMF Article IV 2025: general government tax revenue ≈10.5% of GDP (FY2025)" }, socialSpending: { v: 2, src: "ILO World Social Protection Report 2024–26: ≈2% of GDP" },
    militarySpending: 2.7, topTaxRate: { v: 35, src: "Income Tax Ordinance 2001 (salaried top slab 35%)" }, religiousPolicy: { v: "favor", src: "Constitution of Pakistan: Islam is the state religion (Pew 2017: official religion)" }, electionYears: 5,
    familyPlanning: { v: 0.4, src: "UN World Population Policies: policy to lower fertility; Population Welfare Programme" }, institutionalTrust: null, lastCoup: 1999,
    faiths: [{ profile: "muslim_south_asia", share: 96.35 }, { profile: "hindu_minority_south_asia", share: 1.61 }, { profile: "christian_south_asia", share: 1.37 }],
    faithSource: "Pakistan Bureau of Statistics, 7th Population and Housing Census 2023",
    groupFertility: null,
  },
  {
    id: "bangladesh", name: "Bangladesh", iso: "BGD",
    population: 178880000, popGrowth: 1.19, gdpPPP: 10955, growth: 4.7,
    tfr: { v: 2.09, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 75.5, medianAge: 27.5, netMigration: -2.09,
    ageBands: [0.09441, 0.08961, 0.08775, 0.09313, 0.09277, 0.08488, 0.07984, 0.06837, 0.07004, 0.05493, 0.04547, 0.03827, 0.03127, 0.02505, 0.01931, 0.01258, 0.00762, 0.00342, 0.00108, 0.00019, 1e-05],
    urban: 41.2, meanSchooling: 6.8, expectedSchooling: 12.3, freedomHouse: 44,
    vdem: { polyarchy: 0.195, rule: 0.311, freexp: 0.527, clphy: 0.582, clpol: 0.636, gender: 0.537, polarization: 2.366, exclusion: 0.679, religiousFreedom: 1.133, stateOwnership: 0.741, propertyRights: 0.896 },
    electorate: { econ: 0.503, auth: 0.808, patriot: 0.669, year: 2018 },
    government: { label: "BNP government (Tarique Rahman, prime minister since February 2026)", party: "BNP", year: 2008, social: 0.437, econ: 0.71, auth: 0.65, relig: 0.644, patriot: 0.688 },
    religionImportant: { v: 97, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 5, src: "Not covered by Pew; set near the South Asian Muslim-majority level (Pakistan 2%, Indonesia 9%) — estimate" }, socialTrust: { v: 13, src: "World Values Survey wave 7 (2018)" }, socialMedia: { v: 27.4, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 20, wealthGini: { v: 74, src: "No UBS estimate for Bangladesh: regional proxy (India, UBS 2025)" }, taxRevenue: { v: 7.5, src: "IMF Article IV 2025: tax revenue ≈7.5% of GDP (FY2025)" }, socialSpending: { v: 2, src: "ILO World Social Protection Report 2024–26: ≈2% of GDP" },
    militarySpending: 1.0, topTaxRate: { v: 30, src: "National Board of Revenue, FY2025–26 (top slab 30%)" }, religiousPolicy: { v: "favor", src: "Constitution of Bangladesh: Islam is the state religion (Pew 2017: official religion)" }, electionYears: 5,
    familyPlanning: { v: 0.6, src: "UN World Population Policies: policy to lower fertility; one of the strongest family-planning programmes since the 1970s" }, institutionalTrust: null, lastCoup: 2007,
    faiths: [{ profile: "muslim_south_asia", share: 91.04 }, { profile: "hindu_minority_south_asia", share: 7.95 }, { profile: "buddhist_sea", share: 0.61 }, { profile: "christian_south_asia", share: 0.3 }],
    faithSource: "Bangladesh Bureau of Statistics, Population and Housing Census 2022",
    groupFertility: null,
  },
  {
    id: "indonesia", name: "Indonesia", iso: "IDN",
    population: 288950000, popGrowth: 0.74, gdpPPP: 18973, growth: 5.0,
    tfr: { v: 2.08, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 71.6, medianAge: 31.8, netMigration: -0.14,
    ageBands: [0.07587, 0.07777, 0.08303, 0.08278, 0.07733, 0.07589, 0.07439, 0.072, 0.07188, 0.06853, 0.06184, 0.05454, 0.04471, 0.0335, 0.02212, 0.01267, 0.00717, 0.00307, 0.00081, 0.00011, 1e-05],
    urban: 59.2, meanSchooling: 8.7, expectedSchooling: 13.3, freedomHouse: 56,
    vdem: { polyarchy: 0.462, rule: 0.338, freexp: 0.688, clphy: 0.636, clpol: 0.596, gender: 0.726, polarization: 0.104, exclusion: 0.579, religiousFreedom: 1.277, stateOwnership: -0.268, propertyRights: 0.672 },
    electorate: { econ: 0.416, auth: 0.438, patriot: 0.73, year: 2019 },
    government: { label: "Gerindra-led coalition (Prabowo Subianto, president since October 2024)", party: "Gerindra", year: 2019, social: 0.315, econ: 0.383, auth: 0.725, relig: 0.452, patriot: 0.783 },
    religionImportant: { v: 98, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 9, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 5, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 59.4, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 14, wealthGini: { v: 70, src: "No UBS estimate for Indonesia: median of the UBS 2025 sample (≈0.70)" }, taxRevenue: { v: 10.1, src: "Ministry of Finance: tax ratio ≈10.1% of GDP (2024)" }, socialSpending: { v: 2.5, src: "ILO World Social Protection Report 2024–26: ≈2.5% of GDP" },
    militarySpending: 0.7, topTaxRate: { v: 35, src: "Law 7/2021 on Harmonised Taxation (top rate 35%)" }, religiousPolicy: { v: "neutral", src: "No state religion; six officially recognised religions under Pancasila" }, electionYears: 5,
    familyPlanning: { v: 0.6, src: "UN World Population Policies; national family-planning agency BKKBN since 1970" }, institutionalTrust: null, lastCoup: null,
    faiths: [{ profile: "muslim_sea", share: 87.1 }, { profile: "christian_sea", share: 10.5, name: "Christians (Protestant & Catholic)" }, { profile: "hindu_bali", share: 1.7 }, { profile: "buddhist_eastasia", share: 0.7 }],
    faithSource: "Indonesia Ministry of Home Affairs (Dukcapil) population register 2023",
    groupFertility: null,
  },
  {
    id: "nigeria", name: "Nigeria", iso: "NGA",
    population: 244900000, popGrowth: 2.03, gdpPPP: 9994, growth: 4.1,
    tfr: { v: 4.8, src: "Nigeria Demographic and Health Survey 2023–24" }, lifeExp: 55.0, medianAge: 19.5, netMigration: -0.01,
    ageBands: [0.14227, 0.12974, 0.12563, 0.11417, 0.09883, 0.07849, 0.06408, 0.05405, 0.04709, 0.0403, 0.0318, 0.02413, 0.0184, 0.01346, 0.00897, 0.00513, 0.00249, 0.00081, 0.00016, 2e-05, 0.0],
    urban: 54.9, meanSchooling: 7.6, expectedSchooling: 10.5, freedomHouse: 44,
    vdem: { polyarchy: 0.505, rule: 0.289, freexp: 0.849, clphy: 0.327, clpol: 0.863, gender: 0.732, polarization: -0.594, exclusion: 0.52, religiousFreedom: 1.474, stateOwnership: 1.361, propertyRights: 0.742 },
    electorate: { econ: 0.422, auth: 0.372, patriot: 0.495, year: 2019 },
    government: { label: "APC government (Bola Tinubu, president since 2023)", party: "APC", year: 2019, social: 0.291, econ: 0.301, auth: 0.458, relig: 0.451, patriot: 0.542 },
    religionImportant: { v: 93, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 7, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 31, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 33.8, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 30, wealthGini: { v: 70, src: "No UBS estimate for Nigeria: median of the UBS 2025 sample (≈0.70)" }, taxRevenue: { v: 7, src: "IMF Article IV 2025: general government revenue from taxes ≈7% of GDP (after the 2025 GDP rebasing)" }, socialSpending: { v: 0.7, src: "ILO World Social Protection Report 2024–26: <1% of GDP" },
    militarySpending: 0.6, topTaxRate: { v: 25, src: "Nigeria Tax Act 2025 (top personal rate 25% from 2026)" }, religiousPolicy: { v: "neutral", src: "Constitution of Nigeria: no state religion (Sharia penal codes in 12 northern states)" }, electionYears: 4,
    familyPlanning: { v: 0.2, src: "UN World Population Policies: policy to lower fertility; modern contraceptive use ≈12% (NDHS 2023–24)" }, institutionalTrust: { v: 0.25, src: "Gallup World Poll 2022: about a quarter confident in the national government" }, lastCoup: 1993,
    faiths: [{ profile: "muslim_west_africa", share: 56.1 }, { profile: "christian_africa", share: 43.4 }, { profile: "folk_african", share: 0.5 }],
    faithSource: "Pew Research Center 2025 (2020 estimates, based on the Nigeria DHS)",
    groupFertility: null,
  },
  {
    id: "egypt", name: "Egypt", iso: "EGY",
    population: 120970000, popGrowth: 1.44, gdpPPP: 23321, growth: 4.5,
    tfr: { v: 2.68, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 72.2, medianAge: 25.8, netMigration: -0.43,
    ageBands: [0.09886, 0.10008, 0.10969, 0.09498, 0.08354, 0.07741, 0.07154, 0.07138, 0.06528, 0.05545, 0.04625, 0.03869, 0.03177, 0.02419, 0.01646, 0.00918, 0.00383, 0.00114, 0.00025, 3e-05, 0.0],
    urban: 43.0, meanSchooling: 10.1, expectedSchooling: 13.1, freedomHouse: 18,
    vdem: { polyarchy: 0.187, rule: 0.321, freexp: 0.179, clphy: 0.22, clpol: 0.145, gender: 0.547, polarization: -0.22, exclusion: 0.374, religiousFreedom: -1.029, stateOwnership: -1.136, propertyRights: 0.642 },
    electorate: { econ: 0.512, auth: 0.396, patriot: 0.777, year: 2015 },
    government: { label: "Abdel Fattah el-Sisi (president since 2014; military-backed)", party: "NFP", year: 2015, social: 0.291, econ: 0.505, auth: 0.621, relig: 0.361, patriot: 0.894 },
    religionImportant: { v: 90, src: "Derived from Gallup World Poll (97% say religion is important in daily life); Pew has no recent figure" }, acceptHomosexuality: { v: 3, src: "Pew Research Center Global Attitudes 2013" }, socialTrust: { v: 7, src: "World Values Survey wave 7 (2018)" }, socialMedia: { v: 41.2, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 25, wealthGini: { v: 70, src: "No UBS estimate for Egypt: median of the UBS 2025 sample (≈0.70)" }, taxRevenue: { v: 12.5, src: "IMF Article IV 2025: tax revenue ≈12.5% of GDP (FY2024/25)" }, socialSpending: { v: 4, src: "ILO World Social Protection Report 2024–26: ≈4% of GDP" },
    militarySpending: 1.0, topTaxRate: { v: 27.5, src: "Income Tax Law 91/2005 as amended (top rate 27.5%)" }, religiousPolicy: { v: "favor", src: "Constitution of Egypt: Islam is the state religion; Sharia is the principal source of law" }, electionYears: 6,
    familyPlanning: { v: 0.4, src: "UN World Population Policies: policy to lower fertility; national family-planning programme" }, institutionalTrust: null, lastCoup: 2013,
    faiths: [{ profile: "muslim_mena", share: 94.9 }, { profile: "christian_mena", share: 5.1, name: "Christians (mostly Coptic)" }],
    faithSource: "Pew Research Center 2025 (2020 estimates); Coptic Church estimates are higher (≈10%)",
    groupFertility: null,
  },
  {
    id: "turkey", name: "Türkiye", iso: "TUR",
    population: 88060000, popGrowth: 0.3, gdpPPP: 46672, growth: 3.4,
    tfr: { v: 1.48, src: "TurkStat Birth Statistics 2024" }, lifeExp: 78.4, medianAge: 35.2, netMigration: -2.48,
    ageBands: [0.05885, 0.06839, 0.07622, 0.07289, 0.06764, 0.07758, 0.0758, 0.07375, 0.07356, 0.07528, 0.06424, 0.05329, 0.05168, 0.03835, 0.03221, 0.02072, 0.01151, 0.00551, 0.00203, 0.00045, 5e-05],
    urban: 77.6, meanSchooling: 8.9, expectedSchooling: 19.7, freedomHouse: 32,
    vdem: { polyarchy: 0.293, rule: 0.157, freexp: 0.179, clphy: 0.499, clpol: 0.263, gender: 0.558, polarization: 3.362, exclusion: 0.713, religiousFreedom: -0.589, stateOwnership: 0.934, propertyRights: 0.629 },
    electorate: { econ: 0.576, auth: 0.583, patriot: 0.657, year: 2018 },
    government: { label: "People's Alliance, AKP–MHP (Recep Tayyip Erdoğan, president since 2014)", party: "People's All...", year: 2018, social: 0.176, econ: 0.746, auth: 0.977, relig: 0.783, patriot: 0.605 },
    religionImportant: { v: 71, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 25, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 14, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 64.8, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 37, wealthGini: { v: 73, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 21, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 12, src: "OECD Social Expenditure Database (≈12% of GDP)" },
    militarySpending: 1.9, topTaxRate: { v: 40, src: "Income Tax Law 193 (top rate 40%)" }, religiousPolicy: { v: "favor", src: "Constitutionally secular, but the state Diyanet funds and directs Sunni Islam" }, electionYears: 5,
    familyPlanning: { v: 0, src: "Pronatalist policy (2025 declared the Year of the Family): no programme to lower fertility" }, institutionalTrust: null, lastCoup: 1980,
    faiths: [{ profile: "muslim_turkey", share: 95.0 }, { profile: "none_muslim_world", share: 4.5 }, { profile: "christian_mena", share: 0.3 }],
    faithSource: "Pew Research Center 2025 religious-switching survey (95% of adults Muslim, most of the rest unaffiliated)",
    groupFertility: null,
  },
  {
    id: "usa", name: "United States", iso: "USA",
    population: 349890000, popGrowth: 0.49, gdpPPP: 94430, growth: 2.3,
    tfr: { v: 1.62, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 79.8, medianAge: 39.8, netMigration: 3.38,
    ageBands: [0.05333, 0.05503, 0.05978, 0.06442, 0.06799, 0.0655, 0.06657, 0.06985, 0.06676, 0.06332, 0.05737, 0.0594, 0.06004, 0.0585, 0.04935, 0.03801, 0.02447, 0.01282, 0.00566, 0.00159, 0.00022],
    urban: 83.5, meanSchooling: 13.9, expectedSchooling: 15.9, freedomHouse: 81,
    vdem: { polyarchy: 0.735, rule: 0.924, freexp: 0.729, clphy: 0.789, clpol: 0.865, gender: 0.829, polarization: 2.3, exclusion: 0.169, religiousFreedom: 0.953, stateOwnership: 1.755, propertyRights: 0.844 },
    electorate: { econ: 0.543, auth: 0.222, patriot: 0.431, year: 2018 },
    government: { label: "Republican administration (Donald Trump, president since January 2025)", party: "Rep", year: 2018, social: 0.378, econ: 0.751, auth: 0.545, relig: 0.591, patriot: 0.726 },
    religionImportant: { v: 44, src: "Pew Research Center Religious Landscape Study 2023–24" }, acceptHomosexuality: { v: 72, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 55, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 81.1, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 91, wealthGini: { v: 77, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 25.2, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 22.7, src: "OECD Social Expenditure Database (public social spending, 2022, % of GDP)" },
    militarySpending: 3.4, topTaxRate: { v: 37, src: "Internal Revenue Code (federal top rate 37%, plus state taxes)" }, religiousPolicy: { v: "neutral", src: "First Amendment: no established religion" }, electionYears: 4,
    familyPlanning: { v: 0, src: "No national policy to lower fertility" }, institutionalTrust: { v: 0.22, src: "Pew Research Center 2024: 22% trust the federal government most of the time" }, lastCoup: null,
    faiths: [{ profile: "evangelical", share: 23, name: "Evangelical Protestants" }, { profile: "christian_us", share: 38, name: "Other Christians (Catholic, mainline, Black Protestant…)" }, { profile: "none_west", share: 29, name: "Religiously unaffiliated" }, { profile: "jewish_diaspora", share: 2 }, { profile: "muslim_us", share: 1 }, { profile: "hindu_diaspora", share: 1 }, { profile: "buddhist_eastasia", share: 1 }],
    faithSource: "Pew Research Center Religious Landscape Study 2023–24",
    groupFertility: { ref: ["none_west"], tfr: { none_west: 1.6, evangelical: 1.9, christian_us: 1.9 }, src: "Pew Research Center 2022, \"Modeling the Future of Religion in America\" (2020–25): Christian women 1.9, religiously unaffiliated 1.6" },
  },
  {
    id: "uk", name: "United Kingdom", iso: "GBR",
    population: 70110000, popGrowth: 0.52, gdpPPP: 67585, growth: 0.8,
    tfr: { v: 1.41, src: "ONS Births in England and Wales 2024" }, lifeExp: 81.7, medianAge: 41.3, netMigration: 5.21,
    ageBands: [0.0502, 0.05475, 0.06099, 0.06195, 0.06008, 0.0625, 0.06633, 0.06583, 0.06613, 0.06191, 0.06156, 0.06549, 0.06162, 0.05495, 0.04677, 0.04297, 0.02943, 0.01668, 0.00755, 0.00203, 0.00027],
    urban: 84.8, meanSchooling: 13.5, expectedSchooling: 17.8, freedomHouse: 91,
    vdem: { polyarchy: 0.772, rule: 0.955, freexp: 0.833, clphy: 0.897, clpol: 0.858, gender: 0.838, polarization: -0.281, exclusion: 0.135, religiousFreedom: 0.703, stateOwnership: 1.467, propertyRights: 0.858 },
    electorate: { econ: 0.498, auth: 0.087, patriot: 0.471, year: 2019 },
    government: { label: "Labour government (Andy Burnham, prime minister since July 2026)", party: "Lab", year: 2019, social: 0.73, econ: 0.171, auth: 0.363, relig: 0.034, patriot: 0.373 },
    religionImportant: { v: 10, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 86, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 64, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 81.3, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 89, wealthGini: { v: 59, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 35.3, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 22.1, src: "OECD Social Expenditure Database (public social spending, 2022, % of GDP)" },
    militarySpending: 2.3, topTaxRate: { v: 45, src: "HMRC additional rate 45%" }, religiousPolicy: { v: "neutral", src: "Established Church of England is largely symbolic; high religious freedom (V-Dem)" }, electionYears: 5,
    familyPlanning: { v: 0, src: "No national policy to lower fertility" }, institutionalTrust: { v: 0.27, src: "OECD Trust Survey 2024: ≈27% trust the national government" }, lastCoup: null,
    faiths: [{ profile: "christian_weurope", share: 49.4 }, { profile: "none_west", share: 40.3 }, { profile: "muslim_europe", share: 6.4 }, { profile: "hindu_diaspora", share: 1.7 }, { profile: "sikh", share: 0.9 }, { profile: "jewish_diaspora", share: 0.5 }, { profile: "buddhist_eastasia", share: 0.5 }],
    faithSource: "Censuses 2021 (England & Wales, Northern Ireland) and 2022 (Scotland), excluding \"not stated\"",
    groupFertility: { ref: ["christian_weurope", "none_west"], tfr: { christian_weurope: 1.8, none_west: 1.8, muslim_europe: 2.9 }, src: "Pew Research Center 2017, \"Europe's Growing Muslim Population\" (2015–20): Muslim women 2.9, non-Muslim women 1.8" },
  },
  {
    id: "germany", name: "Germany", iso: "DEU",
    population: 83550000, popGrowth: -0.23, gdpPPP: 76747, growth: 0.8,
    tfr: { v: 1.35, src: "Destatis 2024" }, lifeExp: 81.9, medianAge: 46.8, netMigration: 1.89,
    ageBands: [0.04266, 0.04842, 0.04749, 0.0465, 0.04909, 0.05399, 0.05794, 0.06677, 0.0645, 0.06231, 0.0591, 0.07505, 0.08124, 0.0698, 0.05634, 0.04554, 0.03186, 0.02843, 0.01047, 0.00225, 0.00025],
    urban: 77.8, meanSchooling: 14.3, expectedSchooling: 17.3, freedomHouse: 93,
    vdem: { polyarchy: 0.828, rule: 0.991, freexp: 0.914, clphy: 0.983, clpol: 0.892, gender: 0.942, polarization: 0.191, exclusion: 0.022, religiousFreedom: 2.087, stateOwnership: 1.959, propertyRights: 0.968 },
    electorate: { econ: 0.49, auth: 0.077, patriot: 0.356, year: 2017 },
    government: { label: "CDU/CSU–SPD coalition (Friedrich Merz, chancellor since May 2025)", party: "SPD", year: 2017, social: 0.688, econ: 0.49, auth: 0.099, relig: 0.246, patriot: 0.344 },
    religionImportant: { v: 11, src: "Pew Research Center 2018 (2024 survey: under 20%)" }, acceptHomosexuality: { v: 86, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 72, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 79.0, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 67, wealthGini: { v: 67, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 38.0, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 26.7, src: "OECD Social Expenditure Database (public social spending, 2022, % of GDP)" },
    militarySpending: 1.9, topTaxRate: { v: 45, src: "Einkommensteuergesetz: 45% plus solidarity surcharge" }, religiousPolicy: { v: "neutral", src: "Basic Law: no state church (cooperative church–state model)" }, electionYears: 4,
    familyPlanning: { v: 0, src: "No national policy to lower fertility" }, institutionalTrust: { v: 0.39, src: "OECD Trust Survey 2024: ≈39% trust the national government" }, lastCoup: null,
    faiths: [{ profile: "christian_weurope", share: 48.5 }, { profile: "none_west", share: 44.6 }, { profile: "muslim_europe", share: 6.6 }, { profile: "jewish_diaspora", share: 0.15 }],
    faithSource: "German Bishops' Conference and EKD membership statistics 2024; BAMF study on Muslims (5.3–5.6 million); fowid",
    groupFertility: { ref: ["christian_weurope", "none_west"], tfr: { christian_weurope: 1.4, none_west: 1.4, muslim_europe: 1.9 }, src: "Pew Research Center 2017, \"Europe's Growing Muslim Population\" (2015–20): Muslim women 1.9, non-Muslim women 1.4" },
  },
  {
    id: "france", name: "France", iso: "FRA",
    population: 66790000, popGrowth: 0.14, gdpPPP: 68563, growth: 0.9,
    tfr: { v: 1.56, src: "INSEE, Bilan démographique 2025" }, lifeExp: 83.7, medianAge: 43.5, netMigration: 1.33,
    ageBands: [0.04861, 0.05163, 0.05807, 0.06213, 0.06436, 0.06032, 0.0547, 0.05841, 0.05942, 0.06189, 0.06294, 0.06351, 0.06286, 0.05929, 0.05462, 0.05024, 0.03191, 0.0197, 0.01126, 0.00361, 0.00054],
    urban: 82.0, meanSchooling: 11.7, expectedSchooling: 16.0, freedomHouse: 89,
    vdem: { polyarchy: 0.865, rule: 0.967, freexp: 0.959, clphy: 0.943, clpol: 0.953, gender: 0.929, polarization: 1.43, exclusion: 0.158, religiousFreedom: 1.603, stateOwnership: 1.048, propertyRights: 0.946 },
    electorate: { econ: 0.512, auth: 0.079, patriot: 0.469, year: 2017 },
    government: { label: "Centrist government (Emmanuel Macron, president since 2017; PM Sébastien Lecornu)", party: "LaREM", year: 2017, social: 0.681, econ: 0.602, auth: 0.15, relig: 0.025, patriot: 0.457 },
    religionImportant: { v: 18, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 86, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 44, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 79.1, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 71, wealthGini: { v: 57, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 43.8, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 31.6, src: "OECD Social Expenditure Database (public social spending, 2022, % of GDP)" },
    militarySpending: 2.1, topTaxRate: { v: 45, src: "Code général des impôts: 45% plus 3–4% high-income contribution" }, religiousPolicy: { v: "neutral", src: "Laïcité (1905 law): strict separation of state and religion" }, electionYears: 5,
    familyPlanning: { v: 0, src: "No national policy to lower fertility" }, institutionalTrust: { v: 0.29, src: "OECD Trust Survey 2024: ≈29% trust the national government" }, lastCoup: null,
    faiths: [{ profile: "christian_weurope", share: 46 }, { profile: "none_west", share: 43 }, { profile: "muslim_europe", share: 9 }, { profile: "jewish_diaspora", share: 0.6 }, { profile: "buddhist_eastasia", share: 0.5 }],
    faithSource: "Pew Research Center 2025 (2020 estimates)",
    groupFertility: { ref: ["christian_weurope", "none_west"], tfr: { christian_weurope: 1.9, none_west: 1.9, muslim_europe: 2.9 }, src: "Pew Research Center 2017, \"Europe's Growing Muslim Population\" (2015–20): Muslim women 2.9, non-Muslim women 1.9" },
  },
  {
    id: "israel", name: "Israel", iso: "ISR",
    population: 9710000, popGrowth: 1.36, gdpPPP: 59095, growth: 3.9,
    tfr: { v: 2.9, src: "Israel Central Bureau of Statistics 2024" }, lifeExp: 82.9, medianAge: 30.3, netMigration: 1.35,
    ageBands: [0.08891, 0.09084, 0.08806, 0.08193, 0.07719, 0.06953, 0.06301, 0.0605, 0.05889, 0.05555, 0.05304, 0.04499, 0.03888, 0.03603, 0.0329, 0.02808, 0.01593, 0.00953, 0.00445, 0.00142, 0.00032],
    urban: 91.5, meanSchooling: 13.5, expectedSchooling: 14.9, freedomHouse: 73,
    vdem: { polyarchy: 0.694, rule: 0.889, freexp: 0.822, clphy: 0.807, clpol: 0.769, gender: 0.862, polarization: 0.021, exclusion: 0.295, religiousFreedom: 1.364, stateOwnership: 1.226, propertyRights: 0.885 },
    electorate: { econ: 0.546, auth: 0.082, patriot: 0.701, year: 2019 },
    government: { label: "Likud-led coalition (Benjamin Netanyahu, prime minister since December 2022); election due 27 October 2026", party: "L", year: 2019, social: 0.379, econ: 0.708, auth: 0.48, relig: 0.34, patriot: 0.762 },
    religionImportant: { v: 37, src: "Pew Research Center, spring 2024 survey of 36 countries: religion \"very important\"" }, acceptHomosexuality: { v: 47, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 49, src: "Pew Research Center, spring 2024 survey (published Dec 2025): \"most people can be trusted\"" }, socialMedia: { v: 70, src: "DataReportal Digital 2026 (≈70%, estimate)" },
    individualism: 54, wealthGini: { v: 66, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 29.5, src: "OECD Revenue Statistics 2025 (total tax revenue, 2023, % of GDP)" }, socialSpending: { v: 16.5, src: "OECD Social Expenditure Database (public social spending, 2022, % of GDP)" },
    militarySpending: 8.8, topTaxRate: { v: 50, src: "Income Tax Ordinance: 47% plus 3% surtax" }, religiousPolicy: { v: "favor", src: "Jewish state; religious courts govern marriage (Pew 2017: favoured religion)" }, electionYears: 4,
    familyPlanning: { v: 0, src: "Pronatalist policy: no programme to lower fertility" }, institutionalTrust: null, lastCoup: null,
    faiths: [{ profile: "jewish_israel", share: 61.5, name: "Jews (non-Haredi)" }, { profile: "jewish_orthodox", share: 14.3, name: "Haredi Jews" }, { profile: "muslim_mena", share: 18.4, name: "Muslims" }, { profile: "christian_mena", share: 2.0 }, { profile: "druze", share: 1.6 }, { profile: "none_west", share: 2.2, name: "No religion recorded" }],
    faithSource: "Israel Central Bureau of Statistics, end of 2025 (Jews & others 78.3%, Arabs 21.7%); Haredi share 14.3% (Israel Democracy Institute)",
    groupFertility: { ref: ["jewish_israel"], tfr: { jewish_israel: 2.2, jewish_orthodox: 6.5, muslim_mena: 2.75, christian_mena: 1.61, druze: 1.66, none_west: 1.13 }, src: "Haredi (6.5) and other Jewish women (2.2): Israel Democracy Institute, Statistical Report on Ultra-Orthodox Society 2024 (2021–23); Muslim, Christian, Druze and no religion: Israel Central Bureau of Statistics 2024" },
  },
  {
    id: "brazil", name: "Brazil", iso: "BRA",
    population: 213920000, popGrowth: 0.34, gdpPPP: 24428, growth: 1.9,
    tfr: { v: 1.59, src: "UN World Population Prospects 2024 (2026)" }, lifeExp: 76.4, medianAge: 36.5, netMigration: -0.96,
    ageBands: [0.05895, 0.06384, 0.06686, 0.06762, 0.07067, 0.07541, 0.07478, 0.07582, 0.07799, 0.07324, 0.06428, 0.05686, 0.05228, 0.04375, 0.03314, 0.02256, 0.01284, 0.00636, 0.0022, 0.00048, 5e-05],
    urban: 88.0, meanSchooling: 8.4, expectedSchooling: 15.8, freedomHouse: 73,
    vdem: { polyarchy: 0.784, rule: 0.862, freexp: 0.91, clphy: 0.81, clpol: 0.932, gender: 0.818, polarization: 3.224, exclusion: 0.197, religiousFreedom: 2.183, stateOwnership: 1.182, propertyRights: 0.808 },
    electorate: { econ: 0.62, auth: 0.208, patriot: 0.484, year: 2018 },
    government: { label: "PT-led government (Luiz Inácio Lula da Silva, president since 2023); election 4 October 2026", party: "PT", year: 2018, social: 0.741, econ: 0.231, auth: 0.254, relig: 0.014, patriot: 0.195 },
    religionImportant: { v: 72, src: "Pew Research Center 2018 (2024: 87% of Brazilian Christians)" }, acceptHomosexuality: { v: 67, src: "Pew Research Center Global Attitudes 2019 (\"homosexuality should be accepted\")" }, socialTrust: { v: 20, src: "Pew Research Center spring 2024 (under 25%; ≈20%)" }, socialMedia: { v: 67.9, src: "DataReportal, Digital 2026 (active social media user identities / population)" },
    individualism: 38, wealthGini: { v: 81, src: "UBS Global Wealth Report 2025 (wealth Gini)" }, taxRevenue: { v: 32, src: "OECD Revenue Statistics in Latin America 2025 (≈32% of GDP)" }, socialSpending: { v: 16, src: "ILO World Social Protection Report 2024–26: ≈16% of GDP" },
    militarySpending: 1.1, topTaxRate: { v: 27.5, src: "Receita Federal (top rate 27.5%)" }, religiousPolicy: { v: "neutral", src: "Constitution of Brazil: secular state" }, electionYears: 4,
    familyPlanning: { v: 0, src: "No national policy to lower fertility" }, institutionalTrust: null, lastCoup: 1964,
    faiths: [{ profile: "catholic_latam", share: 56.7 }, { profile: "evangelical", share: 26.9, name: "Evangelicals" }, { profile: "none_west", share: 9.3, name: "No religion" }, { profile: "spiritist_brazil", share: 2.8 }],
    faithSource: "IBGE, Census 2022 religion results (published June 2025), people aged 10+",
    groupFertility: null,
  },
];
